// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	User     string
	UserLink string
}{
	User:     "user",
	UserLink: "user_link",
}
